/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WhatWebFX;

import org.junit.Test;
import static org.junit.Assert.*;

public class WhatWebFXTest {
    @Test public void testAppHasAGreeting() {
       
    }
}
